export const ACTIONS = {
  REGISTER_FAILURE: "REGISTER_FAILURE",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  ADD_AVATAR: "ADD_AVATAR",

  ADD_TODO: "ADD_TODO",
  CHECK_TODO: "CHECK_TODO",
  DELETE_TODO: "DELETE_TODO",

  ADD_TASKS: "ADD_TASKS",
  CHECK_TASKS: "CHECK_TASKS",
  DELETE_TASKS: "DELETE_TASKS",
};
