export const ACTIONS = {
  REGISTER_FAILURE: "REGISTER_FAILURE",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  ADD_TODO: "ADD_TODO",
  CHECK: "CHECK",
  DELETE: "DELETE",

  ADD_TASKS: "ADD_TASKS",
  CHECK_TASKS: "CHECK_TASKS",
  DELETE_TASKS: "DELETE_TASKS",
};
